name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main


jobs:
  build:
      strategy:
        matrix:
          include:
            - { target: linux-64,       os: ubuntu-20.04 }
            - { target: linux-aarch64,  os: ubuntu-latest }
            - { target: win-64,         os: windows-latest }
            - { target: osx-64,         os: macos-latest }
            - { target: osx-arm64,      os: macos-14 }
        fail-fast: false
      runs-on: ${{ matrix.os }}
      steps:
      - uses: actions/checkout@v4
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.6
        with:
          artifact-name: rpi-imager-${{ matrix.target }}
          build-args: --target-platform ${{ matrix.target }}${{ matrix.target == 'linux-aarch64' && ' --no-test' || '' }}
      - name: Upload all packages
        shell: bash
        # do not upload on PR
        if: github.event_name == 'push'
        env:
          PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
        run: |
          # ignore errors because we want to ignore duplicate packages
          for file in output/**/*.conda; do
            rattler-build upload prefix -c ruben-arts "$file" || true
          done
